services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    volumes:
      - ./data:/data:rw
    environment:
      DATABASE_URL: sqlite:////data/app.db
    command:
      - bash
      - -c
      - |
        flask db upgrade
        flask run --host=0.0.0.0
