services:

  tailwindcss:
    build:
      context: .
      dockerfile: Dockerfile.tailwindcss
    volumes:
      - .:/source
    tty: true
    command:
      - bash
      - -c
      - |
        tailwindcss -i app/static/tailwind.css -o app/static/style.css --watch


  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/source
    ports:
      - 5000:5000
    environment:
      FLASK_APP: server:app
    command:
      - bash
      - -c
      - |
        cd /source
        flask run --host=0.0.0.0 --debug
